language: groovy
sudo: required

jdk:
  - oraclejdk8

script: ./gradlew build --stacktrace --no-daemon

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    packages:
      - oracle-java8-installer
